//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class User
    {
        public int id { get; set; }
        [Required(ErrorMessage = "This Field is required.")]

        //name
        [RegularExpression(@"^[a-zA-Z\u00C0-\u00FF ]{3,50}$",
        ErrorMessage = "Please enter a valid name.")]
        public string name { get; set; }

        [Required(ErrorMessage = "This Field is required.")]
        [DataType(DataType.Password)]
        [RegularExpression(@"^(?=.*\d)[a-zA-Z\d]{3,12}$",
           ErrorMessage = "Please enter a valid password.")]
        public string password { get; set; }

        //password
        [Compare("password", ErrorMessage = "The password and confirmation password do not match.")]
        [Required(ErrorMessage = "This Field is required.")]
        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        public string ConfirmPassword { get; set; }

        //email
        [Required(ErrorMessage = "This Field is required.")]
        [RegularExpression(@"^[a-z0-9]([a-z0-9]+\.?)*@[a-z]+\.[a-z]{2,3}$",
                            ErrorMessage = "Please enter a valid email address")]
        public string email { get; set; }
        public string test { get; set; }
    }
}
